# Generated by Django 5.1.5 on 2025-04-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_sales_count_alter_product_digital_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sales_count',
        ),
        migrations.AlterField(
            model_name='product',
            name='digital',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
